name: Terraform CI/CD

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  AWS_REGION: eu-west-2
  TF_IN_AUTOMATION: true

permissions:
  id-token: write   # For AWS OIDC
  contents: read

jobs:

  terraform-plan:
    name: Terraform Plan (PR)
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::508261694247:role/GithubTerraformRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        env:
          GIT_PAT: ${{ secrets.GIT_AUTH_PAT }}
        run: terraform init -var="GIT_PAT=${GIT_PAT}"

      - name: Terraform Validate
        working-directory: terraform
        env:
          GIT_PAT: ${{ secrets.GIT_AUTH_PAT }}
        run: terraform validate -var="GIT_PAT=${GIT_PAT}"

      - name: Terraform Plan
        working-directory: terraform
        env:
          GIT_PAT: ${{ secrets.GIT_AUTH_PAT }}
        run: terraform plan -var="GIT_PAT=${GIT_PAT}" -var-file="terraform.tfvars"

  terraform-apply:
    name: Terraform Apply (Main Merge)
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: terraform-plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::508261694247:role/GithubTerraformRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        env:
          GIT_PAT: ${{ secrets.GIT_AUTH_PAT }}
        run: terraform init -var="GIT_PAT=${GIT_PAT}"

      - name: Terraform Apply
        working-directory: terraform
        env:
          GIT_PAT: ${{ secrets.GIT_AUTH_PAT }}
        run: terraform apply -auto-approve -var="GIT_PAT=${GIT_PAT}" -var-file="terraform.tfvars"
